# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Authos.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(692, 543)
        self.back_button = QtWidgets.QPushButton(Form)
        self.back_button.setGeometry(QtCore.QRect(10, 490, 151, 41))
        self.back_button.setStyleSheet("font: 22pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);")
        self.back_button.setObjectName("back_button")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 651, 191))
        self.label.setStyleSheet("font: 15pt \"Berlin Sans FB\"; color: rgb(175,238,238);\\nbackground-color: rgb(204, 204, 204, 0);")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Об Авторах"))
        self.back_button.setText(_translate("Form", "Назад"))
        self.label.setText(_translate("Form", "В разработке игры участвовали:\n"
"Войнов Богдан - Backend разработчик,\n"
"Соков Владислав - Frontend разработчик,\n"
"Брянцева Софья - Дизайнер."))
