# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Learning2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1076, 650)
        self.back_button = QtWidgets.QPushButton(Form)
        self.back_button.setGeometry(QtCore.QRect(20, 580, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.back_button.setFont(font)
        self.back_button.setStyleSheet("font: 22pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);")
        self.back_button.setObjectName("back_button")
        self.next_btn = QtWidgets.QPushButton(Form)
        self.next_btn.setGeometry(QtCore.QRect(880, 580, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.next_btn.setFont(font)
        self.next_btn.setStyleSheet("font: 22pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);")
        self.next_btn.setObjectName("next_btn")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1051, 551))
        self.label_2.setStyleSheet("font: 22pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.back_button.setText(_translate("Form", "Назад"))
        self.next_btn.setText(_translate("Form", "Далее"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">В игре есть ядро, которое нужно защищать от атак врагов.</p><p align=\"center\">Сам персонаж, к сожелению стрелять не может, </p><p align=\"center\">но когда-нибудь он научится...</p></body></html>"))
