# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Start_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Flight_Of_The_Clones(object):
    def setupUi(self, Flight_Of_The_Clones):
        Flight_Of_The_Clones.setObjectName("Flight_Of_The_Clones")
        Flight_Of_The_Clones.resize(1076, 650)
        Flight_Of_The_Clones.setStyleSheet("background-color: rgb(62, 130, 255);")
        self.centralwidget = QtWidgets.QWidget(Flight_Of_The_Clones)
        self.centralwidget.setObjectName("centralwidget")
        self.Btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_play.setGeometry(QtCore.QRect(420, 370, 211, 61))
        self.Btn_play.setStyleSheet("font: 22pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);")
        self.Btn_play.setCheckable(False)
        self.Btn_play.setObjectName("Btn_play")
        self.Button_best = QtWidgets.QPushButton(self.centralwidget)
        self.Button_best.setGeometry(QtCore.QRect(790, 10, 261, 81))
        self.Button_best.setStyleSheet("font: 18pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204,0);")
        self.Button_best.setObjectName("Button_best")
        self.Authors = QtWidgets.QPushButton(self.centralwidget)
        self.Authors.setGeometry(QtCore.QRect(30, 10, 261, 81))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Authors.setFont(font)
        self.Authors.setStyleSheet("font: 18pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);\n"
"")
        self.Authors.setObjectName("Authors")
        self.dowloand_button = QtWidgets.QPushButton(self.centralwidget)
        self.dowloand_button.setGeometry(QtCore.QRect(380, 440, 301, 61))
        self.dowloand_button.setStyleSheet("font: 22pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);")
        self.dowloand_button.setObjectName("dowloand_button")
        self.learn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.learn_btn.setGeometry(QtCore.QRect(870, 590, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.learn_btn.setFont(font)
        self.learn_btn.setStyleSheet("font: 22pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);")
        self.learn_btn.setObjectName("learn_btn")
        Flight_Of_The_Clones.setCentralWidget(self.centralwidget)

        self.retranslateUi(Flight_Of_The_Clones)
        QtCore.QMetaObject.connectSlotsByName(Flight_Of_The_Clones)

    def retranslateUi(self, Flight_Of_The_Clones):
        _translate = QtCore.QCoreApplication.translate
        Flight_Of_The_Clones.setWindowTitle(_translate("Flight_Of_The_Clones", "MainWindow"))
        self.Btn_play.setText(_translate("Flight_Of_The_Clones", "Новый мир"))
        self.Button_best.setText(_translate("Flight_Of_The_Clones", "Лучшие игроки"))
        self.Authors.setText(_translate("Flight_Of_The_Clones", "О разработчиках"))
        self.dowloand_button.setText(_translate("Flight_Of_The_Clones", "Загрузить мир"))
        self.learn_btn.setText(_translate("Flight_Of_The_Clones", "Обучение"))
