# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'end.ui'
#
# Created by: PyQt5 UIWindow code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(0, 330, 391, 161))
        self.label_name.setStyleSheet("font: 22pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);")
        self.label_name.setObjectName("label_name")
        self.textEdit_name = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_name.setGeometry(QtCore.QRect(420, 396, 371, 41))
        self.textEdit_name.setObjectName("textEdit_name")
        self.labe_ura = QtWidgets.QLabel(self.centralwidget)
        self.labe_ura.setGeometry(QtCore.QRect(80, 10, 631, 81))
        self.labe_ura.setStyleSheet("font: 22pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);")
        self.labe_ura.setObjectName("labe_ura")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(640, 530, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(10, 110, 781, 211))
        self.label_info.setStyleSheet("font: 16pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);")
        self.label_info.setObjectName("label_info")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Окончание"))
        self.label_name.setText(_translate("MainWindow", "Введите ваше имя:"))
        self.labe_ura.setText(_translate("MainWindow", "Поздравляем, вы заокнчили игру!"))
        self.pushButton.setText(_translate("MainWindow", "Выйти"))
        self.label_info.setText(_translate("MainWindow", "Общее время игры: минут, секунд. Уровень: \n"
"Ключ генерации на котором вы  играли:"))
