# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Old_world.ui'
#
# Created by: PyQt5 UIWindow code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1076, 623)
        self.back_button = QtWidgets.QPushButton(Form)
        self.back_button.setGeometry(QtCore.QRect(20, 550, 111, 41))
        self.back_button.setStyleSheet("font: 22pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);")
        self.back_button.setObjectName("back_button")
        self.label_zag = QtWidgets.QLabel(Form)
        self.label_zag.setGeometry(QtCore.QRect(330, 30, 471, 91))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_zag.setFont(font)
        self.label_zag.setStyleSheet("font: 22pt \"Berlin Sans FB\"; color: rgb(175,238,238);")
        self.label_zag.setObjectName("label_zag")
        self.pushvper = QtWidgets.QPushButton(Form)
        self.pushvper.setGeometry(QtCore.QRect(980, 80, 93, 341))
        self.pushvper.setStyleSheet("font: 42pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);")
        self.pushvper.setObjectName("pushvper")
        self.pushnaz = QtWidgets.QPushButton(Form)
        self.pushnaz.setGeometry(QtCore.QRect(0, 80, 93, 371))
        self.pushnaz.setStyleSheet("font: 42pt \"Berlin Sans FB\"; color: rgb(175,238,238);\n"
"background-color: rgb(204, 204, 204, 0);")
        self.pushnaz.setObjectName("pushnaz")


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Существующий мир"))
        self.back_button.setText(_translate("Form", "Назад"))
        self.label_zag.setText(_translate("Form", "Выберите мир"))
        self.pushvper.setText(_translate("Form", ">"))
        self.pushnaz.setText(_translate("Form", "<"))
